<?php
	/**
		* @var \Blueskytechco\GiftCard\Block\Card $block
	*/
    use Magento\Framework\App\Action\Action;
	$_productCollection = $block->_getProduct();
	$widget_title = $block->getData('title');
	$widget_description = $block->getData('description');
?>
<div class="giftcard giftcard-widget">
	<div class="giftcard__header">
		<?php if ($widget_title) { ?>
			<h2 class="giftcard__title"><?= $widget_title ?></h2>
		<?php } ?>
		<?php if ($widget_description) { ?>
			<p class="giftcard__description"><?= $widget_description ?></p>
		<?php } ?>
	</div>
    <?php if($_productCollection->getSize()){ ?>
	<?php
        $type = 'widget-product-giftcard-grid';
        $mode = 'grid';
        $image = 'new_products_content_widget_grid';
        $showWishlist = true;
        $showCompare = true;
    ?>
	<ol class="elementor__content row product-items <?= /* @noEscape */ $type ?>">
        <?php $iterator = 1; ?>
        <?php foreach ($_productCollection as $_item): ?>
            <li class="product-item">
                <div class="product-item-info">
    				<div class="product_item_images">
    					<a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>" class="product-item-photo">
    						<?= $block->getImage($_item, $image)->toHtml() ?>
    					</a>
    					<?php if ($showWishlist || $showCompare): ?>
                            <div class="product-item-inner">
                                <div class="product-item-actions">
                                    <?php if ($showWishlist || $showCompare): ?>
                                        <div class="actions-secondary" data-role="add-to-links">
                                            <?php if ($this->helper(\Magento\Wishlist\Helper\Data::class)->isAllow() && $showWishlist): ?>
                                                <a href="#"
                                                   data-post='<?= /* @noEscape */ $block->getAddToWishlistParams($_item) ?>' class="action towishlist" data-action="add-to-wishlist" title="<?= $block->escapeHtmlAttr(__('Add to Wish List')) ?>">
                                                    <span><?= $block->escapeHtml(__('Add to Wish List')) ?></span>
                                                </a>
                                            <?php endif; ?>
                                            <?php if ($block->getAddToCompareUrl() && $showCompare): ?>
                                                <?php $compareHelper = $this->helper(\Magento\Catalog\Helper\Product\Compare::class);?>
                                                <a href="#" class="action tocompare" data-post='<?= /* @noEscape */ $compareHelper->getPostDataParams($_item) ?>' title="<?= $block->escapeHtmlAttr(__('Add to Compare')) ?>">
                                                    <span><?= $block->escapeHtml(__('Add to Compare')) ?></span>
                                                </a>
                                            <?php endif; ?>
                                        </div>
                                    <?php endif; ?>
                                </div>
                            </div>
                        <?php endif; ?>
    				</div>
                    <div class="product-item-details">
                        <strong class="product-item-name">
                            <a title="<?= $block->escapeHtml($_item->getName()) ?>"
                               href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="product-item-link">
                                <?= $block->escapeHtml($_item->getName()) ?>
                            </a>
                        </strong>
                        <?= /* @noEscape */ $block->getProductPrice($_item) ?>
                        <div class="card-quick-add">
                            <a href="<?= $block->escapeUrl($block->getProductUrl($_item)) ?>"
                               class="action primary">
                                <span class="not-change atc-text">
                                    <?= $escaper->escapeHtml(__('Quick Add')) ?>
                                </span>
                            </a>
                        </div>
                    </div>
                </div>
            </li>
        <?php endforeach ?>
    </ol>
    <?php }else{ ?>
	<div class="message info empty">
        <div><?= $escaper->escapeHtml(__('No products were found matching your condition.')) ?></div>
    </div>
	<?php } ?>
</div>

